### PR TITLE
Add "Related Organizations" section, with links to the JuliaHealth organization

### PR DESCRIPTION
**Pull request by DilumAluthge**
@BenJWard @jakobnissen I was wondering if you'd be open to the idea of adding a link to the JuliaHealth organization on the BioJulia website?

I've put together this PR as an example. Definitely feel free to edit the PR, make the links less obtrusive, etc.

Let me know what you think!

---

This pull request:
1. Creates the "Related Organizations" section
2. In the "Related Organizations" section, adds a link to the JuliaHealth organization
3.  In the "Related Organizations" section, adds a link to the page on the JuliaHealth website that has a full list of Julia organizations related to the life sciences and health sciences.

You will notice that this pull request also tweaks some of the weights. This was necessary to make sure that the sections appear in the same order as they currently do on the BioJulia website.

### CODE REVIEW

**Review by TransGirlCodes — APPROVED** [review]

**Comment by DilumAluthge** [comment]
I inadvertently made a bunch of whitespace changes. Undoing them now.

**Comment by TransGirlCodes** [comment]
Hey @DilumAluthge I'm more than happy for there to be such a section. Just let me know when you're ready to merge!

**Comment by DilumAluthge** [comment]
Take a look now, I think it should be good to go!

**Review by TransGirlCodes — APPROVED** [review]

**Comment by TransGirlCodes** [comment]
All done, it will become visible when gh-pages regenerates the site.

**Pull request merged**
